server:
  port: 9010
spring:
  application:
    name: api-proxy-app
  # ???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root@123456
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123456 # ??Redis??
      database: 0 # ???0????????????
      timeout: 3000ms # ??????

# MyBatis-Plus ??
mybatis-plus:
  # Mapper XML???????????SQL??
  mapper-locations: classpath*:/mapper/**/*.xml
  # ????????????
  type-aliases-package: com.famsun.gpdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL???????????
  global-config:
    db-config:
      id-type: auto # ?????auto=??????MySQL?????????assign_id??ID